### ISSUE TITLE
Getting crash on iOS 8 with arm64

### ISSUE THREAD

**Issue by nirav99254** [bengottlieb/Twitter-OAuth-iPhone#122]
@bengottlieb:

I have tried to run your demo project with my consumer key and secret, i have used iPhone 5S with iOS 8.1.3.

Every app crash on launch.

I want to update one of my app that is using this library since 2.5 years, so before updating app on appstore i want to make sure library is still works on arm64.

![screen shot 2015-02-16 at 3 26 39 pm](https://cloud.githubusercontent.com/assets/1610634/6209900/61891e24-b5f0-11e4-8d54-22f50921f81d.png)

**Comment by nirav99254** [comment]
@bengottlieb : One more interesting thing is, its only crashes on devices with 64 bit chips. it works perfectly on my iPad mini. Can you test on any of the device with 64bit processor. 

Please let me know your thoughts about the issue.

**Comment by bengottlieb** [comment]
I just pushed up a few changes that should address both these issues.

**Comment by nirav99254** [comment]
You are very helpful my friend.

Thank you so much for your kind help.

On Monday, February 16, 2015, Ben Gottlieb notifications@github.com wrote:

> Closed #122
> https://github.com/bengottlieb/Twitter-OAuth-iPhone/issues/122.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bengottlieb/Twitter-OAuth-iPhone/issues/122#event-236400849
> .

## 

Thanks & Regards
Nirav Limbasiya
iOS Developer
+91 9016 6939 15
